### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by yunwz** [xiaoymin/knife4j#119]
使用IDEA启动项目无异常，打包成jar包启动就报错了。
信息如下:
2019-07-01 17:12:37 ERROR com.github.xiaoymin.swaggerbootstrapui.util.CommonUtils : by java.lang.ClassFormatError: Illegal field name "" in class com/github/xiaoymin/swaggerbootstrapui/model/testcontroller/Test

javassist.CannotCompileException: by java.lang.ClassFormatError: Illegal field name "" in class com/github/xiaoymin/swaggerbootstrapui/model/testcontroller/Test
        at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:271)
        at javassist.ClassPool.toClass(ClassPool.java:1232)
        at javassist.ClassPool.toClass(ClassPool.java:1090)
        at javassist.ClassPool.toClass(ClassPool.java:1048)
        at javassist.CtClass.toClass(CtClass.java:1290)
        at com.github.xiaoymin.swaggerbootstrapui.util.CommonUtils.createDynamicModelClass(CommonUtils.java:147)
        at com.github.xiaoymin.swaggerbootstrapui.plugin.OperationDynamicModelProvider.collectDynamicParameter(OperationDynamicModelProvider.java:96)
        at com.github.xiaoymin.swaggerbootstrapui.plugin.OperationDynamicModelProvider.apply(OperationDynamicModelProvider.java:60)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.modelContexts(DocumentationPluginsManager.java:136)
        at springfox.documentation.spring.web.scanners.ApiModelReader.read(ApiModelReader.java:65)
        at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:133)
        at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:71)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:101)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:167)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:885)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1277)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1265)
        at com.demo.DemoApplication.main(DemoApplication.java:22)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.ClassFormatError: Illegal field name "" in class com/github/xiaoymin/swaggerbootstrapui/model/testcontroller/Test
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
        at javassist.util.proxy.DefineClassHelper$Java7.defineClass(DefineClassHelper.java:177)
        at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:260)
        ... 36 common frames omitted

2019-07-01 17:12:37 ERROR springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper : Unable to scan documentation context default

**java.lang.NullPointerException: null
        at com.fasterxml.classmate.TypeResolver._fromAny(TypeResolver.java:333)
        at com.fasterxml.classmate.TypeResolver.resolve(TypeResolver.java:174)
        at com.fasterxml.classmate.TypeResolver.resolve(TypeResolver.java:132)
        at com.github.xiaoymin.swaggerbootstrapui.plugin.OperationDynamicModelProvider.collectDynamicParameter(OperationDynamicModelProvider.java:97)
        at** com.github.xiaoymin.swaggerbootstrapui.plugin.OperationDynamicModelProvider.apply(OperationDynamicModelProvider.java:60)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.modelContexts(DocumentationPluginsManager.java:136)
        at springfox.documentation.spring.web.scanners.ApiModelReader.read(ApiModelReader.java:65)
        at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:133)
        at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:71)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:101)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:167)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:885)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1277)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1265)
        at com.demo.DemoApplication.main(DemoApplication.java:22)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

**Comment by xiaoymin** [comment]
是不是使用@DynamicParameters注解？

**Comment by xiaoymin** [comment]
https://gitee.com/xiaoym/swagger-bootstrap-ui/issues/IYLVC

**Comment by xiaoymin** [comment]
试试新版本1.9.5
