### ISSUE TITLE
访问/v2/api-docs?group=xxx总会报json序列化异常（虽然似乎是返回正常的swagger.json）

### ISSUE THREAD

**Issue by xinhaiCai** [xiaoymin/knife4j#210]
`2020-04-08 17:32:04,745 WARN  [http-nio-8082-exec-4] parameters.AbstractSerializableParameter (AbstractSerializableParameter.java:421) - Illegal DefaultValue null for parameter type number
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842) ~[?:1.8.0_181]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_181]
	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_181]
	at java.lang.Double.valueOf(Double.java:502) ~[?:1.8.0_181]
	at io.swagger.models.parameters.AbstractSerializableParameter.getExample(AbstractSerializableParameter.java:414) [swagger-models-1.5.20.jar:1.5.20]
	at sun.reflect.GeneratedMethodAccessor187.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:722) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:643) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) [jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) [jackson-databind-2.9.8.jar:2.9.8]`

推测是默认的example字段为null，而序列化时却会根据字段类型去转化，遇到字段类型为基础数值类型时（或枚举）时，转化为数值类型报错

补充下版本信息
```
    <dependency>
      <groupId>com.github.xiaoymin</groupId>
      <artifactId>swagger-bootstrap-ui</artifactId>
      <version>1.9.6</version>
      <scope>compile</scope>
    </dependency>
```

**Comment by ddpopbb3** [comment]
在你的Swagger2Configuer 里加上这一段
```java
@Bean
    public JacksonModuleRegistrar customizeJacksonModuleRegistrar() {
        return new JacksonModuleRegistrar() {
            @Override
            public void maybeRegisterModule(ObjectMapper objectMapper) {
                objectMapper.addMixIn(AbstractSerializableParameter.class, IgnoreExampleMixIn.class);
            }
        };
    }

    interface IgnoreExampleMixIn {
        @JsonIgnore
        Object getExample();
    }
```

**Comment by xinhaiCai** [comment]
恩，解决了。不过这个解决方式有个前提，就是用的是jackson，恰巧我最近把fastjson（不支持泛型反序列化）替换成了gson（和swagger-bootstrap-ui不能很好适配，有正常生成swagger.json但页面上显示不出来）后又替换成了jackson

**Comment by xinhaiCai** [comment]
这样的话不行，相当于弃用了example，example是需要的，example可以在导入yapi后生成默认值，mock的时候会用上
