### ISSUE TITLE
Annotation @ApiModelProperty can't process dataType  'Integer' when example field is default value. It's easy way to set ZERO for default Number value

### ISSUE THREAD

**Issue by hsky233** [xiaoymin/knife4j#313]
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:601)
	at java.lang.Long.valueOf(Long.java:803)
	at io.swagger.models.parameters.AbstractSerializableParameter.getExample(AbstractSerializableParameter.java:412)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by xiaoymin** [comment]
https://xiaoym.gitee.io/knife4j/faq/format-exception.html

**Comment by hsky233** [comment]
> https://xiaoym.gitee.io/knife4j/faq/format-exception.html

cool thanks .
