### ISSUE TITLE
使用knife4j-openapi3-spring-boot-starter，打开doc.html页面报stackoverflow异常

### ISSUE THREAD

**Issue by john1337** [xiaoymin/knife4j#594]
使用knife4j-openapi3-spring-boot-starter，打开doc.html页面报stackoverflow异常，部分错误信息如下所示：
Caused by: java.lang.StackOverflowError: null
	at org.springframework.util.ObjectUtils.nullSafeHashCode(ObjectUtils.java:423) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.core.ResolvableType.calculateHashCode(ResolvableType.java:938) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.core.ResolvableType.<init>(ResolvableType.java:148) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.core.ResolvableType.forType(ResolvableType.java:1436) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.core.ResolvableType.forType(ResolvableType.java:1405) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.core.ResolvableType.getGenerics(ResolvableType.java:720) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.core.ResolvableType.getGenerics(ResolvableType.java:724) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.core.ResolvableType.hasUnresolvableGenerics(ResolvableType.java:548) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springdoc.core.ReturnTypeParser.resolveType(ReturnTypeParser.java:87) ~[springdoc-openapi-common-1.6.15.jar:1.6.15]
	at org.springdoc.core.ReturnTypeParser.resolveType(ReturnTypeParser.java:93) ~[springdoc-openapi-common-1.6.15.jar:1.6.15]
	at org.springdoc.core.ReturnTypeParser.resolveType(ReturnTypeParser.java:93) ~[springdoc-openapi-common-1.6.15.jar:1.6.1

**Comment by xiaoymin** [comment]
这个错误估计是springdoc解析问题。你可以考虑升级一下springdoc的版本，把knife4j-openapi3-spring-boot-starter中的springdoc排除一下试试

**Comment by john1337** [comment]
已解决，某个返回类没有传入泛型类型
