### ISSUE TITLE
spring-boot-starter-actuator兼容问题

### ISSUE THREAD

**Issue by gzdzss** [xiaoymin/knife4j#612]
version:
knife4j-openapi2-spring-boot-starter :4.1.0

spring-boot-starter-actuator:2.7.2
 

error:
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)

**Comment by xiaoymin** [comment]
参考issues：

- https://gitee.com/xiaoym/knife4j/issues/I5BW82
- https://gitee.com/xiaoym/knife4j/issues/I4JT89

**Comment by gzdzss** [comment]
knife4j-openapi2-spring-boot-starter :4.1.0
换成：
knife4j-openapi3-spring-boot-starter: 4.1.0

目前也已经可以了，需要更换注解
参考：
https://springdoc.org/migrating-from-springfox.html
