### ISSUE TITLE
配置组名后打开 doc.html 报错

### ISSUE THREAD

**Issue by vaulka** [xiaoymin/knife4j#631]
配置了组名 displayname 和 group 名称都为 default，swagger 能正常显示，但是 knife4j 打开报错，看了接口返回的数据都是一致的，前端解析时报错了，具体场景复现如下：

![image](https://github.com/xiaoymin/knife4j/assets/53456132/bde81c85-ea23-4b7d-ae69-a1d01bf05a03)

![image](https://github.com/xiaoymin/knife4j/assets/53456132/735825f0-e7f6-4a8e-a8bf-0e69f9bf0a3b)

![image](https://github.com/xiaoymin/knife4j/assets/53456132/dbab9d5b-d339-4d17-9ae4-2b313fb27909)

报错信息如下：

```
app.51033393.js:1 TypeError: Cannot read properties of null (reading 'id')
    at ze.createGroupElement (app.51033393.js:1:194988)
    at app.51033393.js:1:191062
    at app.51033393.js:1:275986
```

**Comment by vaulka** [comment]
该问题为用户操作异常，组名改掉后，访问旧的 url，旧的 url 还是旧的组名，导致访问失败，该 issues close。
