### ISSUE TITLE
springboot 3 启动报错：Caused by: java.lang.ClassNotFoundException: javax.servlet.Filter 

### ISSUE THREAD

**Issue by lehuqizhong** [xiaoymin/knife4j#667]
环境：
a. springboot 3.1.4
b. knife4j-openapi3-jakarta-spring-boot-starter   4.3.0

启动报错java.lang.ClassNotFoundException: javax.servlet.Filter 
目测是Knife4jAutoConfiguration 里面的ServletSecurityBasicAuthFilter
这个要怎么配置呢  高版本springboot 已经没有了 javax.servlet.Filter

**Comment by xiaoymin** [comment]
你的项目中有遗留老的jar包吧，knife4j-openapi3-jakarta-spring-boot-starter 4.3.0
没有javax.servlet.Filter呢

**Comment by lehuqizhong** [comment]
ServletSecurityBasicAuthFilter这个类里面有  然后这个类在Knife4jAutoConfiguration被用了 不知道那里不对  ServletSecurityBasicAuthFilter被初始化了 就报错

**Comment by xiaoymin** [comment]
> ServletSecurityBasicAuthFilter这个类里面有 然后这个类在Knife4jAutoConfiguration被用了 不知道那里不对 ServletSecurityBasicAuthFilter被初始化了 就报错

我看了一下，是漏了，ConditionalOnMissingBean注解里面漏了，是一个bug。感谢

**Comment by Kyle0820** [comment]
> > ServletSecurityBasicAuthFilter这个类里面有 然后这个类在Knife4jAutoConfiguration被用了 不知道那里不对 ServletSecurityBasicAuthFilter被初始化了 就报错
> 
> 我看了一下，是漏了，ConditionalOnMissingBean注解里面漏了，是一个bug。感谢

你好，knife4j-aggregation-spring-boot-starter也改一下依赖吧，这里也用了javax，pom和堆栈报错如下
```

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.3</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
<dependencies>
<dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
            <version>4.4.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-aggregation-spring-boot-starter</artifactId>
            <version>4.4.0</version>
        </dependency>
</dependencies>

```

```
java.lang.IllegalStateException: Error processing condition on org.springdoc.core.configuration.SpringDocConfiguration$QuerydslProvider.queryDslQuerydslPredicateOperationCustomizer
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[spring-boot-autoconfigure-3.2.3.jar:3.2.3]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:183) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:144) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:120) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:428) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:289) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:349) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:788) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:606) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.3.jar:3.2.3]
	at com.hainayun.lift.App.main(App.java:20) ~[classes/:na]
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.github.xiaoymin.knife4j.aggre.spring.configuration.Knife4jAggregationAutoConfiguration] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@4e0e2f2a]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:483) ~[spring-core-6.1.4.jar:6.1.4]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:360) ~[spring-core-6.1.4.jar:6.1.4]
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:417) ~[spring-core-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$1(AbstractAutowireCapableBeanFactory.java:750) ~[spring-beans-6.1.4.jar:6.1.4]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:749) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:682) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:653) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1644) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:562) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:534) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:247) ~[spring-boot-autoconfigure-3.2.3.jar:3.2.3]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:240) ~[spring-boot-autoconfigure-3.2.3.jar:3.2.3]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:230) ~[spring-boot-autoconfigure-3.2.3.jar:3.2.3]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:183) ~[spring-boot-autoconfigure-3.2.3.jar:3.2.3]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:158) ~[spring-boot-autoconfigure-3.2.3.jar:3.2.3]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-3.2.3.jar:3.2.3]
	... 17 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/servlet/Filter
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2676) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465) ~[spring-core-6.1.4.jar:6.1.4]
	... 33 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.servlet.Filter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[na:na]
	... 37 common frames omitted
```

**Comment by irezm** [comment]
<dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-aggregation-spring-boot-starter</artifactId>
                <version>4.5.0</version>
</dependency>

aggregation 4.5中存在 javax.servlet-api 依赖
<dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <scope>provided</scope>
</dependency>

**Comment by GaoPengLin** [comment]
com.github.xiaoymin knife4j-aggregation-spring-boot-starter 4.5.0
还是存在javax.servlet，javax.servlet-api依赖

**Comment by irezm** [comment]
> com.github.xiaoymin knife4j-aggregation-spring-boot-starter 4.5.0 还是存在javax.servlet，javax.servlet-api依赖

可以换一个方案，自己打包一个html项目，返回swagger数据，
https://github.com/irezm/springboot-knife4j-smart-doc
可以看看我这种处理方式

**Comment by GaoPengLin** [comment]
好的感谢




123
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaoymin/knife4j"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月22日(星期天) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaoymin/knife4j] springboot 3 启动报错：Caused by: java.lang.ClassNotFoundException: javax.servlet.Filter  (Issue #667)






com.github.xiaoymin knife4j-aggregation-spring-boot-starter 4.5.0 还是存在javax.servlet，javax.servlet-api依赖

可以换一个方案，自己打包一个html项目，返回swagger数据，
https://github.com/irezm/springboot-knife4j-smart-doc
可以看看我这种处理方式
